apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        imagePullPolicy: Never
        image: microase2324-gateway
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector: 
    app: gateway
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000